#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=969275089300
BundleId=com.exxyz.crazydoor
ClientId=969275089300.apps.googleusercontent.com

*/

#define kAppID "969275089300"
#define kBundleID "com.exxyz.crazydoor"
#define kClientID "969275089300.apps.googleusercontent.com"

#endif


